### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [mmobin789/Android-Custom-Gallery#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by mmobin789** [comment]
@mansya Sure you can but it must well represent the project and highlight its details.
Additionally, You can star and fork the repo as well.

Thanks.

**Comment by mansya** [comment]
hi sir. I have completed the design for this project. How ? do you like it ? if yes which one do you like?
![Android Custom Gallery](https://user-images.githubusercontent.com/33461607/61133091-ee5cc000-a4e6-11e9-8337-9cc12380ee80.png)

**Comment by mmobin789** [comment]
Hey @mansya 4 looks nice send it over to me so I can add this in project here.
