### ISSUE TITLE
Problem with orientation changes

### ISSUE THREAD

**Issue by blue-peacock** [mmobin789/Android-Custom-Gallery#5]
Hi! Thank you very much for sharing such a great project! 

I have a problem with orientation changes. After a change the screen stays white and does not show any images anymore. But I have no idea how to fix this? Can you please give me a hint? Thanks!

**Comment by mmobin789** [comment]
@blue-peacock I was unable to recreate the issue.
Try on different device and post its specs alongwith issue's reproduction steps.

Thanks.
